# Studying the Initial Parent Property

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import my_lib
import graph_lib
import itertools 

### Getting codewords from file

In [13]:
codewords = np.loadtxt("clique_of_9_words.txt", dtype=np.int)
print(codewords)

[[1 1 1 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 1 0 1 0 1 0 1 0 1 0 0 0 0 0 0 1 1 0 0]
 [1 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 1]
 [0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 1 1 1 1 0]
 [0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 1 0 1 0 1 0 0 0 1]
 [1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1]
 [0 0 0 1 0 0 0 0 0 0 1 1 0 1 1 0 1 1 0 0 0 0 1 0]]


In [101]:
def check_coalition(codewords, n1, n2):
    available_keys = my_lib.bin_or(codewords[n1], codewords[n2])
    num_avail_keys = list();
    for i in np.arange(0, 24, 1):
        if(available_keys[i]==1):
            num_avail_keys.append(i);
    all_pirate_choices = itertools.combinations(num_avail_keys, 8)
    
    for pirate_choice in all_pirate_choices:
        pirate_codeword = np.ndarray(shape=(24,), dtype=np.int)
        for i in np.arange(0, 24, 1):
            if(pirate_choice.count(i) == 1):
                pirate_codeword[i] = 1
            else:
                pirate_codeword[i] = 0
                
        min_distance = 24;
        near_codeword_num = [];
        
        for j in np.arange(0, 9, 1):
            if(min_distance > my_lib.hamming_dist(pirate_codeword, codewords[j])):
                min_distance = my_lib.hamming_dist(pirate_codeword, codewords[j]);
                near_codeword_num = [j];
            elif(min_distance == my_lib.hamming_dist(pirate_codeword, codewords[j])):
                near_codeword_num.append(j);
                
        if(len(near_codeword_num) == 1):
            if((near_codeword_num[0] != n1) and (near_codeword_num[0] != n2)):
                print("\nFAILURE\nPirates detected incorrectly");
                print("Coalition: ", n1, n2, "\nCodeword: ", pirate_codeword, "\nDetected: ", near_codeword_num);
                break;
        if(len(near_codeword_num) == 2): 
            if((near_codeword_num.count(n1) == 0) or (near_codeword_num.count(n2) == 0)):
                print("\nFAILURE\nPirates detected incorrectly")
                print("Coalition: ", n1, n2, "\nCodeword: ", pirate_codeword, "\nDetected: ", near_codeword_num);
                break;
        if(len(near_codeword_num) > 2): 
            if((near_codeword_num.count(n1) == 0) or (near_codeword_num.count(n2) == 0)):
                print("\nFAILURE\nPirates detected incorrectly");
                print("Coalition: ", n1, n2, "\nCodeword: ", pirate_codeword, "\nDetected: ", near_codeword_num);
                break;
    print("Coalition ", n1, n2, "checked: SUCCESS")

In [102]:
def check_all_coalitions(codewords):
    users = [i for i in np.arange(0,9,1)];
    possible_coalitions = itertools.combinations(users, 2)
    
    for coalition in possible_coalitions:
        check_coalition(codewords, coalition[0], coalition[1])        

In [103]:
check_all_coalitions(codewords)

Coalition  0 1 checked: SUCCESS
Coalition  0 2 checked: SUCCESS
Coalition  0 3 checked: SUCCESS
Coalition  0 4 checked: SUCCESS
Coalition  0 5 checked: SUCCESS
Coalition  0 6 checked: SUCCESS
Coalition  0 7 checked: SUCCESS
Coalition  0 8 checked: SUCCESS
Coalition  1 2 checked: SUCCESS
Coalition  1 3 checked: SUCCESS
Coalition  1 4 checked: SUCCESS
Coalition  1 5 checked: SUCCESS
Coalition  1 6 checked: SUCCESS
Coalition  1 7 checked: SUCCESS
Coalition  1 8 checked: SUCCESS
Coalition  2 3 checked: SUCCESS
Coalition  2 4 checked: SUCCESS
Coalition  2 5 checked: SUCCESS
Coalition  2 6 checked: SUCCESS
Coalition  2 7 checked: SUCCESS
Coalition  2 8 checked: SUCCESS
Coalition  3 4 checked: SUCCESS
Coalition  3 5 checked: SUCCESS
Coalition  3 6 checked: SUCCESS
Coalition  3 7 checked: SUCCESS
Coalition  3 8 checked: SUCCESS
Coalition  4 5 checked: SUCCESS
Coalition  4 6 checked: SUCCESS
Coalition  4 7 checked: SUCCESS
Coalition  4 8 checked: SUCCESS
Coalition  5 6 checked: SUCCESS
Coalitio

# Yep! This set of codewords have Initial Parent Property!